apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 360
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            limits:
              volcano.sh/gpu-memory: {{ .Values.gpuMem }}