dependencies:
  - name: taskset
    version: 0.1.0
    condition: taskset.enabled
  - name: framework
    version: 0.1.0
    condition: framework.enabled
  - name: volcano
    version: 0.1.0
    condition: volcano.enabled
  - name: pytorch-operator
    version: 0.1.0
    condition: pytorch-operator.enabled