{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nvidia-gpushare-device-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-gpushare-device-plugin.labels" . | nindent 4 }}
    app.kubernetes.io/component: "nvidia-gpushare-device-plugin"
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nvidia-gpushare-device-plugin.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "nvidia-gpushare-device-plugin"
  endpoints:
  - port: "metrics"
    path: "/metrics"
  namespaceSelector:
    matchNames:
{{- if .Values.namespace }}
    - "{{ .Values.namespace }}"
{{ else }}
    - "{{ .Release.Namespace }}"
{{- end }}
  endpoints:
  - port: "metrics"
    path: "/metrics"
    interval: "{{ .Values.serviceMonitor.interval }}"
{{- end -}}
