apiVersion: v1
appVersion: 0.6.0
description: A Helm chart for the nvidia-gpushare-device-plugin on Kubernetes
home: https://github.com/ruanxingbaozi/k8s-gpushare-device-plugin
sources:
  - https://github.com/ruanxingbaozi/k8s-gpushare-device-plugin
kubeVersion: '>= 1.10.0-0'
name: nvidia-gpushare-device-plugin
type: application
version: 0.6.0
icon: file://../nvidialogo.png
