image:
  repository: ruanxingbaozi/k8s-gpushare-device-plugin
  tag: v0.1.2
  pullPolicy: IfNotPresent

compatWithCPUManager: false

vgpuMemSize: 1

enableNodeSelector: false
nodeSelector:
  key:
  value:

affinity: {}

tolerations:
  # This toleration is deprecated. Kept here for backward compatibility
  # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
