apiVersion: v1
description: A Helm chart for Volcano
name: volcano
version: v1.0.0
appVersion: v1.0.0
icon: file://../volcano-logo.png
home: https://volcano.sh
sources:
  - https://github.com/volcano-sh/volcano
maintainers:
  - name: k82cn
    email: klaus1982.cn@gmail.com
  - name: kevin-wangzefeng
    email: kevinwzf0126@gmail.com
