apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices-sriov
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
        "mode" : "sriov",
        "pfNetdevices": [ {{ .Values.pfNetdevices }} ]
    }